# Generated by Django 3.2.18 on 2023-03-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230328_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersstock',
            name='invested',
        ),
        migrations.AddField(
            model_name='transaction',
            name='acc_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usersstock',
            name='avg_price',
            field=models.FloatField(default=0),
        ),
    ]
