# Generated by Django 3.2.18 on 2023-03-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230331_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='acc_date',
            new_name='date',
        ),
    ]
