# Generated by Django 3.2.18 on 2023-03-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_acc_date_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersstock',
            name='symbol',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersstock',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
