# Generated by Django 3.2.18 on 2023-03-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230331_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersstock',
            name='id1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersstock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
