# Generated by Django 3.2.18 on 2023-03-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230331_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='id1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='symbol',
            field=models.CharField(default='', max_length=100),
        ),
    ]
