# Generated by Django 3.2.18 on 2023-03-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230331_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.FloatField(),
        ),
    ]
